FROM ruby:3.2
RUN apt-get update -y && apt-get install -y build-essential libpq-dev
WORKDIR /app
COPY Gemfile Gemfile.lock /app/
RUN gem install bundler && bundle install || true
COPY . /app
EXPOSE 3000
CMD ["bash", "-lc", "bundle install && rm -f tmp/pids/server.pid && bin/rails db:prepare && bin/rails s -b 0.0.0.0 -p 3000"]
